using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace GeneratorLibrary
{
    [Generator]
    public class SimpleClassInjection : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            IncrementalValuesProvider<ClassDeclarationSyntax> syntaxProvider = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax,
                transform: (ctx, _) => ctx.Node as Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax
            ).Where(x => x != null);

            context.RegisterSourceOutput(syntaxProvider, (productionContext, classSyntax) =>
            {
                string className = classSyntax.Identifier.Text;

                string generatedCode = $@"// <auto-generated />
namespace MyGame.Generated
{{
    public static class {className}Extensions
    {{
        public static void LogGenerated(this {className} obj)
        {{
            UnityEngine.Debug.Log(""Hello from incremental generator for {className}!"");
        }}
    }}
}}";
                productionContext.AddSource($"{className}.g.cs", SourceText.From(generatedCode, Encoding.UTF8));
            });
        }
    }
}